package app

import (
	"bytes"
	"testing"
)

var releasesJSON = []byte(`
[
  {
    "url": "https://api.github.com/repos/gameap/daemon/releases/53747962",
    "assets_url": "https://api.github.com/repos/gameap/daemon/releases/53747962/assets",
    "upload_url": "https://uploads.github.com/repos/gameap/daemon/releases/53747962/assets{?name,label}",
    "html_url": "https://github.com/gameap/daemon/releases/tag/v3.1.0beta2",
    "id": 53747962,
    "author": {
      "login": "et-nik",
      "id": 3670640,
      "node_id": "MDQ6VXNlcjM2NzA2NDA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3670640?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/et-nik",
      "html_url": "https://github.com/et-nik",
      "followers_url": "https://api.github.com/users/et-nik/followers",
      "following_url": "https://api.github.com/users/et-nik/following{/other_user}",
      "gists_url": "https://api.github.com/users/et-nik/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/et-nik/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/et-nik/subscriptions",
      "organizations_url": "https://api.github.com/users/et-nik/orgs",
      "repos_url": "https://api.github.com/users/et-nik/repos",
      "events_url": "https://api.github.com/users/et-nik/events{/privacy}",
      "received_events_url": "https://api.github.com/users/et-nik/received_events",
      "type": "User",
      "site_admin": false
    },
    "node_id": "RE_kwDOGQD4xM4DNCD6",
    "tag_name": "v3.1.0beta2",
    "target_commitish": "master",
    "name": "v3.1.0beta2",
    "draft": false,
    "prerelease": true,
    "created_at": "2021-11-18T20:06:21Z",
    "published_at": "2021-11-19T20:11:32Z",
    "assets": [
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49868221",
        "id": 49868221,
        "node_id": "RA_kwDOGQD4xM4C-O29",
        "name": "gameap-daemon-v3.1.0beta2-linux-amd64.tar.gz",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "application/gzip",
        "state": "uploaded",
        "size": 9483605,
        "download_count": 0,
        "created_at": "2021-11-19T20:12:29Z",
        "updated_at": "2021-11-19T20:12:35Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta2/gameap-daemon-v3.1.0beta2-linux-amd64.tar.gz"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49868226",
        "id": 49868226,
        "node_id": "RA_kwDOGQD4xM4C-O3C",
        "name": "gameap-daemon-v3.1.0beta2-linux-amd64.tar.gz.md5",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "text/plain",
        "state": "uploaded",
        "size": 33,
        "download_count": 0,
        "created_at": "2021-11-19T20:12:35Z",
        "updated_at": "2021-11-19T20:12:36Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta2/gameap-daemon-v3.1.0beta2-linux-amd64.tar.gz.md5"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49868227",
        "id": 49868227,
        "node_id": "RA_kwDOGQD4xM4C-O3D",
        "name": "gameap-daemon-v3.1.0beta2-linux-arm.tar.gz",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "application/gzip",
        "state": "uploaded",
        "size": 8679851,
        "download_count": 0,
        "created_at": "2021-11-19T20:12:36Z",
        "updated_at": "2021-11-19T20:12:37Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta2/gameap-daemon-v3.1.0beta2-linux-arm.tar.gz"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49868236",
        "id": 49868236,
        "node_id": "RA_kwDOGQD4xM4C-O3M",
        "name": "gameap-daemon-v3.1.0beta2-linux-arm.tar.gz.md5",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "text/plain",
        "state": "uploaded",
        "size": 33,
        "download_count": 0,
        "created_at": "2021-11-19T20:12:37Z",
        "updated_at": "2021-11-19T20:12:38Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta2/gameap-daemon-v3.1.0beta2-linux-arm.tar.gz.md5"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49868238",
        "id": 49868238,
        "node_id": "RA_kwDOGQD4xM4C-O3O",
        "name": "gameap-daemon-v3.1.0beta2-linux-arm64.tar.gz",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "application/gzip",
        "state": "uploaded",
        "size": 8722768,
        "download_count": 0,
        "created_at": "2021-11-19T20:12:38Z",
        "updated_at": "2021-11-19T20:12:39Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta2/gameap-daemon-v3.1.0beta2-linux-arm64.tar.gz"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49868240",
        "id": 49868240,
        "node_id": "RA_kwDOGQD4xM4C-O3Q",
        "name": "gameap-daemon-v3.1.0beta2-linux-arm64.tar.gz.md5",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "text/plain",
        "state": "uploaded",
        "size": 33,
        "download_count": 0,
        "created_at": "2021-11-19T20:12:40Z",
        "updated_at": "2021-11-19T20:12:40Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta2/gameap-daemon-v3.1.0beta2-linux-arm64.tar.gz.md5"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49868241",
        "id": 49868241,
        "node_id": "RA_kwDOGQD4xM4C-O3R",
        "name": "gameap-daemon-v3.1.0beta2-windows-arm64.zip",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "application/zip",
        "state": "uploaded",
        "size": 8829342,
        "download_count": 0,
        "created_at": "2021-11-19T20:12:40Z",
        "updated_at": "2021-11-19T20:12:43Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta2/gameap-daemon-v3.1.0beta2-windows-arm64.zip"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49868243",
        "id": 49868243,
        "node_id": "RA_kwDOGQD4xM4C-O3T",
        "name": "gameap-daemon-v3.1.0beta2-windows-386.zip",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "application/zip",
        "state": "uploaded",
        "size": 9197362,
        "download_count": 0,
        "created_at": "2021-11-19T20:12:41Z",
        "updated_at": "2021-11-19T20:12:42Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta2/gameap-daemon-v3.1.0beta2-windows-386.zip"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49868244",
        "id": 49868244,
        "node_id": "RA_kwDOGQD4xM4C-O3U",
        "name": "gameap-daemon-v3.1.0beta2-linux-386.tar.gz",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "application/gzip",
        "state": "uploaded",
        "size": 8963018,
        "download_count": 0,
        "created_at": "2021-11-19T20:12:41Z",
        "updated_at": "2021-11-19T20:12:42Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta2/gameap-daemon-v3.1.0beta2-linux-386.tar.gz"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49868245",
        "id": 49868245,
        "node_id": "RA_kwDOGQD4xM4C-O3V",
        "name": "gameap-daemon-v3.1.0beta2-linux-386.tar.gz.md5",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "text/plain",
        "state": "uploaded",
        "size": 33,
        "download_count": 0,
        "created_at": "2021-11-19T20:12:42Z",
        "updated_at": "2021-11-19T20:12:42Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta2/gameap-daemon-v3.1.0beta2-linux-386.tar.gz.md5"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49868247",
        "id": 49868247,
        "node_id": "RA_kwDOGQD4xM4C-O3X",
        "name": "gameap-daemon-v3.1.0beta2-windows-386.zip.md5",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "text/plain",
        "state": "uploaded",
        "size": 33,
        "download_count": 0,
        "created_at": "2021-11-19T20:12:43Z",
        "updated_at": "2021-11-19T20:12:43Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta2/gameap-daemon-v3.1.0beta2-windows-386.zip.md5"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49868248",
        "id": 49868248,
        "node_id": "RA_kwDOGQD4xM4C-O3Y",
        "name": "gameap-daemon-v3.1.0beta2-windows-amd64.zip",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "application/zip",
        "state": "uploaded",
        "size": 9562987,
        "download_count": 0,
        "created_at": "2021-11-19T20:12:43Z",
        "updated_at": "2021-11-19T20:12:44Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta2/gameap-daemon-v3.1.0beta2-windows-amd64.zip"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49868249",
        "id": 49868249,
        "node_id": "RA_kwDOGQD4xM4C-O3Z",
        "name": "gameap-daemon-v3.1.0beta2-windows-arm64.zip.md5",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "text/plain",
        "state": "uploaded",
        "size": 33,
        "download_count": 0,
        "created_at": "2021-11-19T20:12:44Z",
        "updated_at": "2021-11-19T20:12:44Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta2/gameap-daemon-v3.1.0beta2-windows-arm64.zip.md5"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49868251",
        "id": 49868251,
        "node_id": "RA_kwDOGQD4xM4C-O3b",
        "name": "gameap-daemon-v3.1.0beta2-linux-mips.tar.gz",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "application/gzip",
        "state": "uploaded",
        "size": 8606367,
        "download_count": 0,
        "created_at": "2021-11-19T20:12:44Z",
        "updated_at": "2021-11-19T20:12:45Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta2/gameap-daemon-v3.1.0beta2-linux-mips.tar.gz"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49868252",
        "id": 49868252,
        "node_id": "RA_kwDOGQD4xM4C-O3c",
        "name": "gameap-daemon-v3.1.0beta2-windows-amd64.zip.md5",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "text/plain",
        "state": "uploaded",
        "size": 33,
        "download_count": 0,
        "created_at": "2021-11-19T20:12:45Z",
        "updated_at": "2021-11-19T20:12:45Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta2/gameap-daemon-v3.1.0beta2-windows-amd64.zip.md5"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49868255",
        "id": 49868255,
        "node_id": "RA_kwDOGQD4xM4C-O3f",
        "name": "gameap-daemon-v3.1.0beta2-linux-mips.tar.gz.md5",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "text/plain",
        "state": "uploaded",
        "size": 33,
        "download_count": 0,
        "created_at": "2021-11-19T20:12:46Z",
        "updated_at": "2021-11-19T20:12:46Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta2/gameap-daemon-v3.1.0beta2-linux-mips.tar.gz.md5"
      }
    ],
    "tarball_url": "https://api.github.com/repos/gameap/daemon/tarball/v3.1.0beta2",
    "zipball_url": "https://api.github.com/repos/gameap/daemon/zipball/v3.1.0beta2",
    "body": ""
  },
  {
    "url": "https://api.github.com/repos/gameap/daemon/releases/53671355",
    "assets_url": "https://api.github.com/repos/gameap/daemon/releases/53671355/assets",
    "upload_url": "https://uploads.github.com/repos/gameap/daemon/releases/53671355/assets{?name,label}",
    "html_url": "https://github.com/gameap/daemon/releases/tag/v3.1.0beta1",
    "id": 53671355,
    "author": {
      "login": "et-nik",
      "id": 3670640,
      "node_id": "MDQ6VXNlcjM2NzA2NDA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3670640?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/et-nik",
      "html_url": "https://github.com/et-nik",
      "followers_url": "https://api.github.com/users/et-nik/followers",
      "following_url": "https://api.github.com/users/et-nik/following{/other_user}",
      "gists_url": "https://api.github.com/users/et-nik/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/et-nik/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/et-nik/subscriptions",
      "organizations_url": "https://api.github.com/users/et-nik/orgs",
      "repos_url": "https://api.github.com/users/et-nik/repos",
      "events_url": "https://api.github.com/users/et-nik/events{/privacy}",
      "received_events_url": "https://api.github.com/users/et-nik/received_events",
      "type": "User",
      "site_admin": false
    },
    "node_id": "RE_kwDOGQD4xM4DMvW7",
    "tag_name": "v3.1.0beta1",
    "target_commitish": "master",
    "name": "v3.1.0beta1",
    "draft": false,
    "prerelease": true,
    "created_at": "2021-11-18T20:06:21Z",
    "published_at": "2021-11-18T20:09:31Z",
    "assets": [
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49784584",
        "id": 49784584,
        "node_id": "RA_kwDOGQD4xM4C96cI",
        "name": "gameap-daemon-v3.1.0beta1-linux-mips64.tar.gz",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "application/gzip",
        "state": "uploaded",
        "size": 8697284,
        "download_count": 0,
        "created_at": "2021-11-18T20:10:32Z",
        "updated_at": "2021-11-18T20:10:33Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta1/gameap-daemon-v3.1.0beta1-linux-mips64.tar.gz"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49784586",
        "id": 49784586,
        "node_id": "RA_kwDOGQD4xM4C96cK",
        "name": "gameap-daemon-v3.1.0beta1-linux-mips64.tar.gz.md5",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "text/plain",
        "state": "uploaded",
        "size": 33,
        "download_count": 0,
        "created_at": "2021-11-18T20:10:33Z",
        "updated_at": "2021-11-18T20:10:33Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta1/gameap-daemon-v3.1.0beta1-linux-mips64.tar.gz.md5"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49784587",
        "id": 49784587,
        "node_id": "RA_kwDOGQD4xM4C96cL",
        "name": "gameap-daemon-v3.1.0beta1-linux-386.tar.gz",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "application/gzip",
        "state": "uploaded",
        "size": 8963106,
        "download_count": 0,
        "created_at": "2021-11-18T20:10:34Z",
        "updated_at": "2021-11-18T20:10:35Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta1/gameap-daemon-v3.1.0beta1-linux-386.tar.gz"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49784590",
        "id": 49784590,
        "node_id": "RA_kwDOGQD4xM4C96cO",
        "name": "gameap-daemon-v3.1.0beta1-linux-386.tar.gz.md5",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "text/plain",
        "state": "uploaded",
        "size": 33,
        "download_count": 0,
        "created_at": "2021-11-18T20:10:35Z",
        "updated_at": "2021-11-18T20:10:36Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta1/gameap-daemon-v3.1.0beta1-linux-386.tar.gz.md5"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49784592",
        "id": 49784592,
        "node_id": "RA_kwDOGQD4xM4C96cQ",
        "name": "gameap-daemon-v3.1.0beta1-windows-arm.zip",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "application/zip",
        "state": "uploaded",
        "size": 8845885,
        "download_count": 0,
        "created_at": "2021-11-18T20:10:36Z",
        "updated_at": "2021-11-18T20:10:37Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta1/gameap-daemon-v3.1.0beta1-windows-arm.zip"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49784594",
        "id": 49784594,
        "node_id": "RA_kwDOGQD4xM4C96cS",
        "name": "gameap-daemon-v3.1.0beta1-windows-arm.zip.md5",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "text/plain",
        "state": "uploaded",
        "size": 33,
        "download_count": 0,
        "created_at": "2021-11-18T20:10:38Z",
        "updated_at": "2021-11-18T20:10:38Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta1/gameap-daemon-v3.1.0beta1-windows-arm.zip.md5"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49784596",
        "id": 49784596,
        "node_id": "RA_kwDOGQD4xM4C96cU",
        "name": "gameap-daemon-v3.1.0beta1-windows-386.zip",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "application/zip",
        "state": "uploaded",
        "size": 9197363,
        "download_count": 0,
        "created_at": "2021-11-18T20:10:41Z",
        "updated_at": "2021-11-18T20:10:42Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta1/gameap-daemon-v3.1.0beta1-windows-386.zip"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49784599",
        "id": 49784599,
        "node_id": "RA_kwDOGQD4xM4C96cX",
        "name": "gameap-daemon-v3.1.0beta1-windows-386.zip.md5",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "text/plain",
        "state": "uploaded",
        "size": 33,
        "download_count": 0,
        "created_at": "2021-11-18T20:10:43Z",
        "updated_at": "2021-11-18T20:10:43Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta1/gameap-daemon-v3.1.0beta1-windows-386.zip.md5"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49784606",
        "id": 49784606,
        "node_id": "RA_kwDOGQD4xM4C96ce",
        "name": "gameap-daemon-v3.1.0beta1-windows-amd64.zip",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "application/zip",
        "state": "uploaded",
        "size": 9562983,
        "download_count": 1,
        "created_at": "2021-11-18T20:10:46Z",
        "updated_at": "2021-11-18T20:10:46Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta1/gameap-daemon-v3.1.0beta1-windows-amd64.zip"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49784609",
        "id": 49784609,
        "node_id": "RA_kwDOGQD4xM4C96ch",
        "name": "gameap-daemon-v3.1.0beta1-windows-arm64.zip",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "application/zip",
        "state": "uploaded",
        "size": 8829331,
        "download_count": 0,
        "created_at": "2021-11-18T20:10:46Z",
        "updated_at": "2021-11-18T20:10:47Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta1/gameap-daemon-v3.1.0beta1-windows-arm64.zip"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49784611",
        "id": 49784611,
        "node_id": "RA_kwDOGQD4xM4C96cj",
        "name": "gameap-daemon-v3.1.0beta1-windows-amd64.zip.md5",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "text/plain",
        "state": "uploaded",
        "size": 33,
        "download_count": 0,
        "created_at": "2021-11-18T20:10:47Z",
        "updated_at": "2021-11-18T20:10:47Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta1/gameap-daemon-v3.1.0beta1-windows-amd64.zip.md5"
      },
      {
        "url": "https://api.github.com/repos/gameap/daemon/releases/assets/49784612",
        "id": 49784612,
        "node_id": "RA_kwDOGQD4xM4C96ck",
        "name": "gameap-daemon-v3.1.0beta1-windows-arm64.zip.md5",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false
        },
        "content_type": "text/plain",
        "state": "uploaded",
        "size": 33,
        "download_count": 0,
        "created_at": "2021-11-18T20:10:47Z",
        "updated_at": "2021-11-18T20:10:47Z",
        "browser_download_url": "https://github.com/gameap/daemon/releases/download/v3.1.0beta1/gameap-daemon-v3.1.0beta1-windows-arm64.zip.md5"
      }
    ],
    "tarball_url": "https://api.github.com/repos/gameap/daemon/tarball/v3.1.0beta1",
    "zipball_url": "https://api.github.com/repos/gameap/daemon/zipball/v3.1.0beta1",
    "body": ""
  },
  {
    "url": "https://api.github.com/repos/gameap/daemon/releases/53553723",
    "assets_url": "https://api.github.com/repos/gameap/daemon/releases/53553723/assets",
    "upload_url": "https://uploads.github.com/repos/gameap/daemon/releases/53553723/assets{?name,label}",
    "html_url": "https://github.com/gameap/daemon/releases/tag/v3.1.0alpha3",
    "id": 53553723,
    "author": {
      "login": "et-nik",
      "id": 3670640,
      "node_id": "MDQ6VXNlcjM2NzA2NDA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3670640?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/et-nik",
      "html_url": "https://github.com/et-nik",
      "followers_url": "https://api.github.com/users/et-nik/followers",
      "following_url": "https://api.github.com/users/et-nik/following{/other_user}",
      "gists_url": "https://api.github.com/users/et-nik/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/et-nik/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/et-nik/subscriptions",
      "organizations_url": "https://api.github.com/users/et-nik/orgs",
      "repos_url": "https://api.github.com/users/et-nik/repos",
      "events_url": "https://api.github.com/users/et-nik/events{/privacy}",
      "received_events_url": "https://api.github.com/users/et-nik/received_events",
      "type": "User",
      "site_admin": false
    },
    "node_id": "RE_kwDOGQD4xM4DMSo7",
    "tag_name": "v3.1.0alpha3",
    "target_commitish": "master",
    "name": "v3.1.0alpha3",
    "draft": false,
    "prerelease": true,
    "created_at": "2021-11-17T13:24:23Z",
    "published_at": "2021-11-17T13:25:03Z",
    "assets": [

    ],
    "tarball_url": "https://api.github.com/repos/gameap/daemon/tarball/v3.1.0alpha3",
    "zipball_url": "https://api.github.com/repos/gameap/daemon/zipball/v3.1.0alpha3",
    "body": ""
  }
]
`)

//func TestFindRelease(t *testing.T) {
//	findRelease(releases, )
//}

func Test(t *testing.T) {
	tests := []struct {
		name        string
		os          string
		arch        string
		expectedUrl string
	}{
		{
			"linux-amd64",
			"linux",
			"amd64",
			"https://github.com/gameap/daemon/releases/download/v3.1.0beta2/gameap-daemon-v3.1.0beta2-linux-amd64.tar.gz",
		},
		{
			"linux-mips64",
			"linux",
			"mips64",
			"https://github.com/gameap/daemon/releases/download/v3.1.0beta1/gameap-daemon-v3.1.0beta1-linux-mips64.tar.gz",
		},
		{
			"windows-amd64",
			"windows",
			"amd64",
			"https://github.com/gameap/daemon/releases/download/v3.1.0beta2/gameap-daemon-v3.1.0beta2-windows-amd64.zip",
		},
		{
			"windows-386",
			"windows",
			"386",
			"https://github.com/gameap/daemon/releases/download/v3.1.0beta2/gameap-daemon-v3.1.0beta2-windows-386.zip",
		},
		{
			"invalid",
			"windows",
			"invalid",
			"",
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			reader := bytes.NewReader(releasesJSON)
			result, err := findRelease(reader, test.os, test.arch)

			if err != nil {
				t.Fatal(err)
			}
			if result != test.expectedUrl {
				t.Fatalf("invalid url: %s, want %s", result, test.expectedUrl)
			}
		})
	}
}
